### ISSUE TITLE
Convert interface to use CSS and React colors in addition to GL format

### ISSUE THREAD

**Issue by leoz** [magic-script/magic-script-components#149]
Use middleware like e.g. [chroma.js](https://gka.github.io/chroma.js/) to enable standard [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) and [React Native](https://facebook.github.io/react-native/docs/colors) colors in addition to the GL color notion used currently.

**Comment by leoz** [comment]
[chroma.js](https://gka.github.io/chroma.js/) supports GL colors [directly](https://gka.github.io/chroma.js/#chroma-gl).

**Comment by grozdanov** [comment]
Color property accepts the following values: 
- string: 'hotpink'; '#ff3399'; 'F39'
- number: 0xff3399
- array: [r, g, b, a],
  example GL format: [0.5, 0.25, 0, 0.7], [0.5, 1.25, 2, 0.7]
- object:
  { h:120, s:1, l:0.75 }
  { l:80, c:25, h:200 }
  { c:1, m:0.5, y:0, k:0.2}
  { r:255, g:165, b:0, a: 0.8, type?: 'RGBAVec4' } 
  *if `type` is missing the default interpretation will be as RBGA32.
