### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-components#186]
### Description

Enable applications to launch at any page route.
Example deeplink: `catalog://scene/14`

### Completion status

- [x] [Android](https://github.com/magic-script/magic-script-components-react-native/issues/384)
- [x] [iOS](https://github.com/magic-script/magic-script-components-react-native/issues/384)
- [x] Lumin

**Comment by pleszkiewicz** [comment]
For Android and iOS, we need to expose onAppStart event in the Scene component and pass `uri` param in there. On Lumin, there are more properties passed in the onAppStart event but they are not related/not intuitive and we can ignore them for now.
```
{ 
      uri,
      isInternetConnected,
      isWiFiConnected,
      isWiFiEnabled,
      isShareableApp
}
```
FYI @grzegorzdec @grozdanov @kpiascik @darek607 @SPaluchiewiczSofomo
