### ISSUE TITLE
Panel Documentation doesn't work with CLI template

### ISSUE THREAD

**Issue by kpiascik** [magic-script/magic-script-components#211]
Panel Component just not working trying the exact example from docs with error when using the CLI template

**Comment by kpiascik** [comment]
https://github.com/magic-script/magic-script-cli/search?l=JSON&q=components is using a very old version of the `magic-script-components-lumin` package.

**Comment by kpiascik** [comment]
https://github.com/magic-script/magic-script-cli/issues/122

**Comment by grozdanov** [comment]
MXSCOMP-91
