### ISSUE TITLE
Implement [Button] default values

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-components#223]
| Name      | Type   |      Default Value       | Description                               |
| :-------- | :----- | :----------------------: | ----------------------------------------- |
| iconColor | vec4   | [0.75, 0.75, 0.75, 1.00] | Sets the RGBA color of the button icon.   |
| iconSize  | vec2   |       [0.04, 0.04]       | Sets the button icon size in scene units. |
| textColor | vec4   | [0.75, 0.75, 0.75, 1.00] | Sets the RGBA color of the button text.   |
| textSize  | number |          0.0167          | Sets the text size.                       |

**Comment by grozdanov** [comment]
MXSCOMP-86

**Comment by grzegorzdec** [comment]
size: 1
