### ISSUE TITLE
Implement [DatePicker] showHint property

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-components#224]
- [x] Android 
- [x] IOS 🍎 

| Name     | Type    |    Default Value    |Description  
| :------- | :------ | :----------------: |----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| showHint | boolean |      true        | To show the selected Date eg. 01/01/2019 or the format hint eg. MM/DD/YYYY. This will only have an affect when not currently focused. The full hint is always displayed on creation. Each field will continue to show the hint, ie MM or DD or YYYYY, until that field is focused. This can override that behavior and display the Date immediately if desired. The full Date will be shown when the user confirms a selected Date. |

**Comment by grozdanov** [comment]
MXSCOMP-85

**Comment by grzegorzdec** [comment]
Android size: 1

**Comment by grzegorzdec** [comment]
Basically, when `showHint` is false `defaultDate` should be shown as a hint instead of pattern. 
android fix pr with screenshot: https://github.com/magic-script/magic-script-components-react-native/pull/443
