### ISSUE TITLE
fix [Toggle] type property

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-components#235]
Currently "type" means one of "switch, checkbox, radio" but regarding documentation, it should contain the position of the label 

| Name   | Type   | Default Value | Required | Description                                                                                                     |
| ------ | ------ | :-----------: | :------: | --------------------------------------------------------------------------------------------------------------- |
| type   | string |     `top`     |          | The location of the toggle label. Only placing the label to top and left of the toggle are currently supported. |

**Comment by grozdanov** [comment]
MXSCOMP-74

**Comment by darek607** [comment]
It's not an Android specific issue. The `type` is used by Lumin and iOS and can be one of: switch, checkbox or radio. I think we should update documentation for this. Also if we want to support label position we should name it like `labelPosition` but not `type`.

**Comment by grzegorzdec** [comment]
@kpiascik
