### ISSUE TITLE
Update [WebView] default properties

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-components#237]
| Name   | Type   | Default Value | Required | Description               |
| ------ | ------ | :-----------: | :------: | ------------------------- |
| width  | number |      `0`      |    N     | The width of the WebView. |
| height | number |      `0`      |    N     | the width of the WebView. |

**Comment by grozdanov** [comment]
MXSCOMP-72

**Comment by darek607** [comment]
@grozdanov If we do not specify the width or height for webview it should be invisible?
