### ISSUE TITLE
Color picker is showing on empty pageview/rect layout

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-components#247]
Reproducible in the `sample-magic-script-components-docs` - `https://github.com/magic-script/magic-script-samples` branch `magic_script_components_examples`

scenes: 
 - toggle
![ios](https://user-images.githubusercontent.com/13310911/74741690-94cb2980-525d-11ea-84ba-ebf02d7ccb12.png)
- tab
![ios](https://user-images.githubusercontent.com/13310911/74741717-9e549180-525d-11ea-9c2c-64dd9d8eff97.png)
- rectlayout
![ios](https://user-images.githubusercontent.com/13310911/74741766-b0363480-525d-11ea-9136-322e437e366c.png)

**Comment by grozdanov** [comment]
MXSCOMP-70

**Comment by SPaluchiewiczSofomo** [comment]
Fix in PR: https://github.com/magic-script/magic-script-components-react-native/pull/437
