### ISSUE TITLE
ui-node-events typo in onHoverMoveSub

### ISSUE THREAD

**Issue by Ninikitos** [magic-script/magic-script-components#274]
Please correct native event name from onHoveMoveSub to onHoverMoveSub.

File path: node_modules\magic-script-components-lumin\src\platform\lumin-runtime\types\ui-node-events.js

**Comment by grozdanov** [comment]
The master branch has the proper naming: 
https://github.com/magic-script/magic-script-components-lumin/blob/d3837ebebecdc14fd8bded5258aa17f765308bbe/src/platform/lumin-runtime/types/ui-node-events.js#L32

**Comment by Ninikitos** [comment]
Updating to latest version fixed my problem. Ticket can be closed
