### ISSUE TITLE
Image fit property

### ISSUE THREAD

**Issue by pleszkiewicz** [magic-script/magic-script-components#283]
### Description

Provide **fit** property for <Image> component.

The **fit** prop supports the following types:
- aspectFill
- aspectFit
- stretch

![content_mode](https://user-images.githubusercontent.com/199881/78147998-924f1880-7434-11ea-936b-fa69332d5147.png)
[Image source](https://stackoverflow.com/a/24671000)

### JIRA

MXSCOMP-217

### Completion status
- [x] [Android](https://github.com/magic-script/magic-script-components-react-native/issues/518)
- [x] [iOS](https://github.com/magic-script/magic-script-components-react-native/issues/518)
- [x] Lumin

**Comment by grozdanov** [comment]
Resolved for Lumin by: https://github.com/magic-script/magic-script-components-lumin/commit/0f2e90776a601d613b9b3cddbe6c79845950bc0e
