### ISSUE TITLE
Update screenshots for components

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-components#292]
Missing screenshots:

1. CircleConfirmation
2. ColorPicker
3. Dialog
4. Line
5. ScrollBar
6. ScrollView
7. Video
8. Prism (Scene, View, Content)

Components without UI/not implemented fully:

1. Audio
2. Light
3. Quad
4. View
5. PortalIcon

**Comment by kpiascik** [comment]
`Scene` can re-use `Prism` similarly for `View`. 
Quad and Light leave alone for now until we get iOS/Android support.

**Comment by kpiascik** [comment]
Also `PortalIcon` is Lumin only, right?
