### ISSUE TITLE
Pass initial uri parameter in Scene.onAppStart event.

### ISSUE THREAD

**Issue by pleszkiewicz** [magic-script/magic-script-components#294]
### Description

For Android and iOS, we need to expose **onAppStart** event in the **Scene** component and pass `uri` param in there. 

On Lumin, there are more properties passed in the **onAppStart** event but they are not related/not intuitive and we can ignore them for now.
```
{ 
      uri,
      isInternetConnected,
      isWiFiConnected,
      isWiFiEnabled,
      isShareableApp
}
```

### Completion status
- [x] [Android](https://github.com/magic-script/magic-script-components-react-native/issues/538)
- [x] [iOS](https://github.com/magic-script/magic-script-components-react-native/issues/538)

**Comment by grozdanov** [comment]
MXSCOMP-242
