### ISSUE TITLE
WebView doesn't load urls

### ISSUE THREAD

**Issue by kpiascik** [magic-script/magic-script-components#93]
`WebView` component only has width and height properties.  There is no way to specify a URL to load.

**Comment by grozdanov** [comment]
WebView is supposed to work with WebViewClient which is still in the works. WebViewClientis the component which accept the URL.

**Comment by kpiascik** [comment]
https://docs.magicscript.org/api_1.5.0/lumin.ui.UiWebView.html#loadUrl
`loadUrl` is a function on `UiWebView` not the client.

**Comment by grozdanov** [comment]
It is unbelievable how often same actions are named with different verbs among different LRT classes. Most of the time it is "setX()" for setting property but I see that for the WebView setting the URL is done by "loadX".

**Comment by kpiascik** [comment]
The API could be better, but it's easy to hook up at least

**Comment by grozdanov** [comment]
Resolved by: https://github.com/magic-script/magic-script-components-lumin/pull/9/commits/5a74f64f9d7aa90c268a32fb88a22d5685d47952
